### PR TITLE
l10n: Fixed typo

### PR DESCRIPTION
**Pull request by rakekniven**
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Review by Valdnet — APPROVED** [review]

**Comment by rakekniven** [comment]
Do not merge! More to come with this PR.

**Comment by rakekniven** [comment]
Now it is ready. Please review and merge.

**Comment by Valdnet** [comment]
@rakekniven Please see my suggestions 😉.

**Comment by rakekniven** [comment]
> @rakekniven Please see my suggestions 😉.

Where? At GitHub or TX?
🙈

**Review by Valdnet — CHANGES_REQUESTED** [review]

**Comment by Valdnet** [comment]
> Where? At GitHub or TX?

Ok. It was as pending 😁.

**Review by ArtificialOwl — APPROVED** [review]

**Comment by ArtificialOwl** [comment]
please rebase, and can we merge it ?

**Review by rakekniven — COMMENTED** [review]
Changes done.

**Review by rakekniven — COMMENTED** [review]
Changes done.

**Review by Valdnet — APPROVED** [review]

**Pull request merged**
