### PR TITLE
Update version on master

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by PVince81** [comment]
node failure. needs rebuild of JS ?

**Comment by ArtificialOwl** [comment]
> node failure. needs rebuild of JS ?

I think @artonge is trying to fix this

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
24 coming with https://github.com/nextcloud/backup/pull/62

**Pull request closed without merging**
