### PR TITLE
confirm data is array

### LINKED ISSUE #380: Unable to fetch restore points - Cannot create one
Hello,

I currently got an error when trying to create a restore point. I was able to add my external storage (storj app) for my backups. As temporary folder for the Restore points I selected Local Storage.
When I try to create a restore point I get this error:
https://pastebin.com/2GEQ8GqZ
Anyone got an Idea how to fix that? 
Or is that still the incompatibly of the backup app with NC 24?

### PR DESCRIPTION
**Pull request by ArtificialOwl**
fix #380

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by sibiantony** [comment]
@ArtificialOwl wouldn't deserializeJson now fail with object types other than arrays? Isn't it better to initialize the restore point on file creation? 

There's a PR here https://github.com/nextcloud/backup/pull/395. Please review.

I somehow missed the original issue and this PR. There's a duplicate issue ticket #394

**Comment by ArtificialOwl** [comment]
I am only interested in arrays in fact. You PR might be a duplicate for this issue, but filling `$metadataFile` at creation and returns it looks good to me also.

**Pull request merged**
